# Generated by Django 5.1.1 on 2024-09-21 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('degree', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('certifications', models.TextField()),
                ('internship_details', models.TextField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('github_profile', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'programminglanguage',
            },
        ),
        migrations.CreateModel(
            name='ECertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.person')),
            ],
            options={
                'db_table': 'ecertificate',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='programming_languages',
            field=models.ManyToManyField(to='core.programminglanguage'),
        ),
    ]
