# Generated by Django 5.1.1 on 2024-09-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_programminglanguage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ecertificate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
    ]
