# Generated by Django 5.1.1 on 2024-09-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programminglanguage',
            old_name='name',
            new_name='language_name',
        ),
    ]
